### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by vredesbyyrd** [thekakkun/music_utilities#1]
Hi, thanks for sharing this. It's a very useful extension. 

I am having trouble getting it to work :/ 

I followed the install instructions, i.e, beets is on version `1.6.1`, python on `3.11.5`,  running on archlinux. 

```python
Traceback (most recent call last):
  File "/home/clu/.python/bin/beet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/clu/.python/lib/python3.11/site-packages/beets/ui/__init__.py", line 1782, in main
    _raw_main(args)
  File "/home/clu/.python/lib/python3.11/site-packages/beets/ui/__init__.py", line 1769, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/clu/.python/lib/python3.11/site-packages/beetsplug/mpd_tracker.py", line 56, in _func
    asyncio.run(self.run(lib))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/clu/.python/lib/python3.11/site-packages/beetsplug/mpd_tracker.py", line 77, in run
    self.set_skipped(lib, song)
  File "/home/clu/.python/lib/python3.11/site-packages/beetsplug/mpd_tracker.py", line 121, in set_skipped
    item["skip_count"] = item.get("skip_count", 0) + 1
                         ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
Exception ignored in: <function StreamWriter.__del__ at 0x7fd184cc1620>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/streams.py", line 396, in __del__
  File "/usr/lib/python3.11/asyncio/streams.py", line 344, in close
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 860, in close
  File "/usr/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
  File "/usr/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
RuntimeError: Event loop is closed
```
If you have any ideas I am all ears! Thanks for your time.

**Comment by thekakkun** [comment]
Hi, thanks for the feedback. Looks like beets is having trouble finding the song via the path.

The path relies on two pieces of data: 
- The parent music directory, stored in the beets config, found via:
   `beet config`
- The relative path to the song, in MPD, found via:
   `mpc -f "%file%" current` (this displays the file path for the current playing song)

These two paths are joined together to specify the song for beets. Can you let me know what those commands return, and how your library is structured?

**Comment by vredesbyyrd** [comment]
Okay, much appreciate the description on how paths are determined. 

The "issue" is my config(s). I set up my beets config years ago, and taking the lazy and unwise route I used 3 separate configs for different "category's" of music. In hindsight not very smart, and it's biting me now. For example, I have three main directories in my `music/` directory:  `Artists/`, `Composers/` & `Scores/`. For each the beets `paths` config option is a little different - which was the motivation for separate config files. 

The `Artists` config looks like: 

```yaml
directory: /mnt/TARS/Media/Music/Artists
library: /mnt/TARS/Media/library.db
paths:
    default: %the{$albumartist}/$year - $album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
````
The `Composers` config:

```yaml
directory: /mnt/TARS/Media/Music/Composers
library: /mnt/TARS/Media/library.db
paths:
    default: %asciify{$albumartist}/$year - %asciify{$album%aunique{}}/%if{$multidisc,Disc $disc/}%asciify{$track - $title}
```

Anyway, this is a config issue on my side, not a `beets-mpd-utils` issue so I will close this. I will just have to take the time to read beets documentation and figure out if there is a sane way to accomplish what my config(s) do now in a single config file.

**Comment by thekakkun** [comment]
Oh, I see. Yeah, that might be outside the scope of the plugin. I assume your MPD setup just points towards `/mnt/TARS/Media/Music`?

All of the stuff below is untested and I don't fully understand how you manage your library, so don't just run the commands willy-nilly, but I'd imagine you could probably implement this using flexible attributes and path styles. 
1. [Specify format for category](https://beets.readthedocs.io/en/stable/guides/advanced.html#choose-a-path-style-manually-for-some-music)
   ```yaml
   paths:
       category:composer:  Composer/%asciify{$albumartist}/$year - %asciify{$album%aunique{}}/%if{$multidisc,Disc $disc/}%asciify{$track - $title}
   ```
3. [Set flexible attributes for your items](https://beets.readthedocs.io/en/stable/guides/advanced.html#store-any-data-you-like)
   `beet modify category="composer" path:/mnt/TARS/Media/Music/Composers`
4. [Move items](https://beets.readthedocs.io/en/stable/faq.html#rename-my-files-according-to-a-new-path-format-configuration)
   `beet move category="composer"`

Good luck!

**Comment by vredesbyyrd** [comment]
> ... I assume your MPD setup just points towards /mnt/TARS/Media/Music?

Correct 

> All of the stuff below is untested and I don't fully understand how you manage your library, so don't just run the commands willy-nilly, but I'd imagine you could probably implement this using flexible attributes and path styles.

Okay, awesome :) Your examples and linked documentation appear to be exactly what I need. Thank you! And yeah I will not do anything reckless, or at least I will read the doc and make sure my backups are clean before I do :) 

Thanks much!

**Comment by vredesbyyrd** [comment]
Hey, Unfortunately, reopening. 

I'm down to a single config now. Having a broad understanding of how the plugin gets a path, it _should_ work, and It is working on some albums, but crashing on others with the same error as before, hmm. 

Here is the relevant part of my config:

```yaml
library: /mnt/TARS/Media/library.db
directory: /mnt/TARS/Media/Music
paths:
    default: Artists/%the{$albumartist}/$year - $album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    category:artists: Artists/%the{$albumartist}/$year - $album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
    category:composers: Composers/%asciify{$albumartist}/$year - %asciify{$album%aunique{}}/%if{$multidisc,Disc $disc/}%asciify{$track - $title}
    category:scores: Scores/%the{$albumartist}/$year - $album%aunique{}/%if{$multidisc,Disc $disc/}$track - $title
```
`mpc -f "%file%" current` for a working file:

`Artists/Agnes Obel/2010 - Philharmonics/02 - Riverside.flac`

`mpc -f "%file%" current` for a file that causes crash:

`Artists/Bonobo/2013 - The North Borders/01 - First Fires.flac`

I see no difference between a working and non-working file, so there has to be something going on that I am overlooking. Any ideas?

**Comment by vredesbyyrd** [comment]
Alright, it has to be something with my database now, so once again on my end.

```bash 
beet ls path:/mnt/TARS/Media/Music/Artists | wc -l
5871
```

```bash
beet ls path::/mnt/TARS/Media/Music/Artists | wc -l
24878
```
Notice the `path::` finds all the files in the directory while `path:` only finds some. Not sure why, i'll dig into it tomorrow with a fresh brain. Sorry for the noise.

**Comment by thekakkun** [comment]
Hmm... I'm not quite sure what's causing that. the double colon changes the query to use regex, but I'm not sure that should change things.

Might be worth asking the folks over at beets.

**Comment by vredesbyyrd** [comment]
So the issue was with my database. Some how most of the items in the `path`  column of the items table were the wrong datatype - `text` when they should be `blob`. Once I fixed that everything is in working order.
