### ISSUE TITLE
Rating in tracker plugin?

### ISSUE THREAD

**Issue by vredesbyyrd** [thekakkun/music_utilities#2]
Hi, 

Would you be open to adding a `rating` key to the tracker plugin, like the [mpdstats](https://beets.readthedocs.io/en/stable/plugins/mpdstats.html) plugin does? mpdstats bases the rating off of play_count and skip_count. That's a useful attribute to have, imo.

I would use mpdstats, but I much prefer how your plugin allows for configuring play_count and skip_count. 

Just an idea!

**Comment by thekakkun** [comment]
Hi again! Unfortunately, this isn't something I'd be interested in implementing.

I do think it would be cool to implement a more generic system for calculated metadata, where values are generated from other pieces of data, but I've got other priorities at the moment.

**Comment by vredesbyyrd** [comment]
No worries, and I appreciate the explanation.
